version: "3.9"  # Specify the Docker Compose version

networks:
  mynet:  # Create a custom network

services:
  database:
    image: mysql:latest  # Use the official MySQL image (you can choose a specific version if needed)
    restart: always  # Restart the container automatically unless manually stopped
    env_file:
      - ./.env  # Load environment variables from the specified file
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Execute the SQL commands when the container starts
      - dbdata:/var/lib/mysql  # Store the MySQL data on the named volume
    ports:
      - "3306:3306"  # Map the container port 3306 to host port 3306
    networks:
      - mynet  # Connect the container to the custom network
  authors-api:
    build: ./blogger-back/authors-api # Build the Dockerfile in the specified directory
    restart: always  # Restart the container automatically unless manually stopped
    env_file:
      - ./blogger-back/authors-api/.env  # Load environment variables from the specified file
    ports: 
      - "8082:8082"  # Map the container port 8082 to host port 8082
    networks:
      - mynet  # Connect the container to the custom network
    depends_on:
      - database  # Wait until the database container is ready before starting this container
  blogs-api:
    build: ./blogger-back/blogs-api # Build the Dockerfile in the specified directory
    restart: always  # Restart the container automatically unless manually stopped
    env_file:
      - ./blogger-back/blogs-api/.env  # Load environment variables from the specified file
    ports: 
      - "8081:8081"  # Map the container port 8081 to host port 8081
    networks:
      - mynet  # Connect the container to the custom network
    depends_on:
      - database  # Wait until the database container is ready before starting this container
  middlend:
    build: ./blogger-back/middlend # Build the Dockerfile in the specified directory
    restart: always # Restart the container automatically unless manually stopped
    env_file:
      - ./blogger-back/middlend/.env  # Load environment variables from the specified file
    ports:
      - "8080:8080"  # Map the container port 8080 to host port 8080
    networks:
      - mynet  # Connect the container to the custom network
    depends_on:
      - authors-api  # Wait until the authors-api container is ready before starting this container
      - blogs-api  # Wait until the blogs-api container is ready before starting this container
  frontend:
    build: ./blogger-front # Build the Dockerfile in the specified directory
    restart: always  # Restart the container automatically unless manually stopped
    env_file:
      - ./blogger-front/.env  # Load environment variables from the specified file
    ports:
      - "3000:3000"  # Map the container port 3000 to host port 3000
    networks:
      - mynet  # Connect the container to the custom network
    depends_on:
      - middlend  # Wait until the middlend container is ready before starting this container
  
volumes:
  dbdata:  # Create a named volume