CREATE DATABASE IF NOT EXISTS blogger_author;
CREATE DATABASE IF NOT EXISTS blogger_blog;

USE blogger_author;
CREATE TABLE IF NOT EXISTS author(
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) DEFAULT '',
	username VARCHAR(50) DEFAULT '',
	email VARCHAR(50) DEFAULT '',
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME,
	delete_at DATETIME
);

USE blogger_blog;
CREATE TABLE IF NOT EXISTS blog(
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(50) DEFAULT '',
	content LONGTEXT,
	author_id INT NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME,
	delete_at DATETIME
);