CREATE TABLE IF NOT EXISTS author(
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) DEFAULT '',
	username VARCHAR(50) DEFAULT '',
	email VARCHAR(50) DEFAULT '',
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME,
	delete_at DATETIME
)