repos:
  - repo: local
    hooks:
      - id: lila-lint
        name: lila-lint
        entry: golangci-lint run -c .golangci.yml --go=1.17
        language: system
        always_run: true
        pass_filenames: false
